{{- $root := . }}
{{- range .Values.users }}
{{- $username := .name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.clusterName }}-{{ $username }}-login
  labels:
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    slurm-user: {{ $username }}
    slurm-cluster: {{ $root.Values.clusterName }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    slurm-user: {{ $username }}
    slurm-cluster: {{ $root.Values.clusterName }}
---
{{- end }}